# Generated by Django 3.0.6 on 2020-05-05 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_post_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='owner',
        ),
    ]
