# Generated by Django 3.0.6 on 2020-05-05 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20200505_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_Name',
            new_name='first_name',
        ),
    ]
